// <auto-generated />
using System;
using GestaoObras.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoObras.Migrations
{
    [DbContext(typeof(AppDb))]
    partial class AppDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestaoObras.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Cliente"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Morada")
                        .HasColumnType("longtext");

                    b.Property<string>("NIF")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GestaoObras.Models.MaoDeObra", b =>
                {
                    b.Property<int>("Id_Mao_Obra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Mao_Obra"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Horas")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("Id_Obra")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ObraId_Obra")
                        .HasColumnType("int");

                    b.HasKey("Id_Mao_Obra");

                    b.HasIndex("ObraId_Obra");

                    b.ToTable("MaoDeObra");
                });

            modelBuilder.Entity("GestaoObras.Models.Material", b =>
                {
                    b.Property<int>("Id_Material")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Material"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stock_Disponivel")
                        .HasColumnType("int");

                    b.HasKey("Id_Material");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("GestaoObras.Models.Movimento", b =>
                {
                    b.Property<int>("Id_Movimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Movimento"));

                    b.Property<DateTime>("Data_Operacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Id_Material")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Obra")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId_Material")
                        .HasColumnType("int");

                    b.Property<int?>("ObraId_Obra")
                        .HasColumnType("int");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id_Movimento");

                    b.HasIndex("MaterialId_Material");

                    b.HasIndex("ObraId_Obra");

                    b.ToTable("Movimentos");
                });

            modelBuilder.Entity("GestaoObras.Models.Obra", b =>
                {
                    b.Property<int>("Id_Obra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Obra"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ClienteId_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int?>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Morada")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Obra");

                    b.HasIndex("ClienteId_Cliente");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("GestaoObras.Models.Pagamento", b =>
                {
                    b.Property<int>("Id_Pagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Pagamento"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Id_Obra")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int?>("ObraId_Obra")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id_Pagamento");

                    b.HasIndex("ObraId_Obra");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("GestaoObras.Models.MaoDeObra", b =>
                {
                    b.HasOne("GestaoObras.Models.Obra", "Obra")
                        .WithMany("MaoDeObra")
                        .HasForeignKey("ObraId_Obra");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("GestaoObras.Models.Movimento", b =>
                {
                    b.HasOne("GestaoObras.Models.Material", "Material")
                        .WithMany("Movimentos")
                        .HasForeignKey("MaterialId_Material");

                    b.HasOne("GestaoObras.Models.Obra", "Obra")
                        .WithMany("Movimentos")
                        .HasForeignKey("ObraId_Obra");

                    b.Navigation("Material");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("GestaoObras.Models.Obra", b =>
                {
                    b.HasOne("GestaoObras.Models.Cliente", "Cliente")
                        .WithMany("Obras")
                        .HasForeignKey("ClienteId_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestaoObras.Models.Pagamento", b =>
                {
                    b.HasOne("GestaoObras.Models.Obra", "Obra")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ObraId_Obra");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("GestaoObras.Models.Cliente", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("GestaoObras.Models.Material", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("GestaoObras.Models.Obra", b =>
                {
                    b.Navigation("MaoDeObra");

                    b.Navigation("Movimentos");

                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
